// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.27.1
// source: security.proto

package securityproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecurityEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp int64             `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level     uint32            `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Type      uint32            `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Pid       uint32            `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	Tid       uint32            `protobuf:"varint,6,opt,name=tid,proto3" json:"tid,omitempty"`
	Uid       uint32            `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Uname     string            `protobuf:"bytes,8,opt,name=uname,proto3" json:"uname,omitempty"`
	PodName   string            `protobuf:"bytes,9,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ExtInfo   map[string]string `protobuf:"bytes,10,rep,name=ext_info,json=extInfo,proto3" json:"ext_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SecurityEvent) Reset() {
	*x = SecurityEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityEvent) ProtoMessage() {}

func (x *SecurityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityEvent.ProtoReflect.Descriptor instead.
func (*SecurityEvent) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SecurityEvent) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SecurityEvent) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SecurityEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SecurityEvent) GetTid() uint32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *SecurityEvent) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SecurityEvent) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *SecurityEvent) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SecurityEvent) GetExtInfo() map[string]string {
	if x != nil {
		return x.ExtInfo
	}
	return nil
}

type SecurityEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events   []*SecurityEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Ip       string           `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname string           `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *SecurityEventRequest) Reset() {
	*x = SecurityEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityEventRequest) ProtoMessage() {}

func (x *SecurityEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityEventRequest.ProtoReflect.Descriptor instead.
func (*SecurityEventRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{1}
}

func (x *SecurityEventRequest) GetEvents() []*SecurityEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SecurityEventRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SecurityEventRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type SecurityEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SecurityEventResponse) Reset() {
	*x = SecurityEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityEventResponse) ProtoMessage() {}

func (x *SecurityEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityEventResponse.ProtoReflect.Descriptor instead.
func (*SecurityEventResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Label struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabelName string   `protobuf:"bytes,1,opt,name=labelName,proto3" json:"labelName,omitempty"`
	Values    []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Label) Reset() {
	*x = Label{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{3}
}

func (x *Label) GetLabelName() string {
	if x != nil {
		return x.LabelName
	}
	return ""
}

func (x *Label) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SecurityConfigFilterFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Perm uint32 `protobuf:"varint,2,opt,name=perm,proto3" json:"perm,omitempty"`
	Op   string `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
}

func (x *SecurityConfigFilterFile) Reset() {
	*x = SecurityConfigFilterFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityConfigFilterFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfigFilterFile) ProtoMessage() {}

func (x *SecurityConfigFilterFile) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfigFilterFile.ProtoReflect.Descriptor instead.
func (*SecurityConfigFilterFile) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{4}
}

func (x *SecurityConfigFilterFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SecurityConfigFilterFile) GetPerm() uint32 {
	if x != nil {
		return x.Perm
	}
	return 0
}

func (x *SecurityConfigFilterFile) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

type SecurityConfigTargetFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels []*Label                    `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Files  []*SecurityConfigFilterFile `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *SecurityConfigTargetFile) Reset() {
	*x = SecurityConfigTargetFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityConfigTargetFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfigTargetFile) ProtoMessage() {}

func (x *SecurityConfigTargetFile) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfigTargetFile.ProtoReflect.Descriptor instead.
func (*SecurityConfigTargetFile) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{5}
}

func (x *SecurityConfigTargetFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityConfigTargetFile) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SecurityConfigTargetFile) GetFiles() []*SecurityConfigFilterFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type SecurityConfigArgFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProbeName string                      `protobuf:"bytes,1,opt,name=probeName,proto3" json:"probeName,omitempty"`
	Targets   []*SecurityConfigTargetFile `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *SecurityConfigArgFile) Reset() {
	*x = SecurityConfigArgFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityConfigArgFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfigArgFile) ProtoMessage() {}

func (x *SecurityConfigArgFile) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfigArgFile.ProtoReflect.Descriptor instead.
func (*SecurityConfigArgFile) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{6}
}

func (x *SecurityConfigArgFile) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *SecurityConfigArgFile) GetTargets() []*SecurityConfigTargetFile {
	if x != nil {
		return x.Targets
	}
	return nil
}

type SecurityConfigProbeFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Probes []*SecurityConfigArgFile `protobuf:"bytes,1,rep,name=probes,proto3" json:"probes,omitempty"`
}

func (x *SecurityConfigProbeFile) Reset() {
	*x = SecurityConfigProbeFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityConfigProbeFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfigProbeFile) ProtoMessage() {}

func (x *SecurityConfigProbeFile) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfigProbeFile.ProtoReflect.Descriptor instead.
func (*SecurityConfigProbeFile) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{7}
}

func (x *SecurityConfigProbeFile) GetProbes() []*SecurityConfigArgFile {
	if x != nil {
		return x.Probes
	}
	return nil
}

type SecurityConfigTargetProcess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels []*Label `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *SecurityConfigTargetProcess) Reset() {
	*x = SecurityConfigTargetProcess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityConfigTargetProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfigTargetProcess) ProtoMessage() {}

func (x *SecurityConfigTargetProcess) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfigTargetProcess.ProtoReflect.Descriptor instead.
func (*SecurityConfigTargetProcess) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{8}
}

func (x *SecurityConfigTargetProcess) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityConfigTargetProcess) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

// 还得修改，把process下的具体的内容表示出来
type SecurityConfigArgProcess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProbeName string                         `protobuf:"bytes,1,opt,name=probeName,proto3" json:"probeName,omitempty"`
	Targets   []*SecurityConfigTargetProcess `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *SecurityConfigArgProcess) Reset() {
	*x = SecurityConfigArgProcess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityConfigArgProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfigArgProcess) ProtoMessage() {}

func (x *SecurityConfigArgProcess) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfigArgProcess.ProtoReflect.Descriptor instead.
func (*SecurityConfigArgProcess) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{9}
}

func (x *SecurityConfigArgProcess) GetProbeName() string {
	if x != nil {
		return x.ProbeName
	}
	return ""
}

func (x *SecurityConfigArgProcess) GetTargets() []*SecurityConfigTargetProcess {
	if x != nil {
		return x.Targets
	}
	return nil
}

type SecurityConfigProbeProcess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Probes []*SecurityConfigArgProcess `protobuf:"bytes,1,rep,name=probes,proto3" json:"probes,omitempty"`
}

func (x *SecurityConfigProbeProcess) Reset() {
	*x = SecurityConfigProbeProcess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityConfigProbeProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfigProbeProcess) ProtoMessage() {}

func (x *SecurityConfigProbeProcess) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfigProbeProcess.ProtoReflect.Descriptor instead.
func (*SecurityConfigProbeProcess) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{10}
}

func (x *SecurityConfigProbeProcess) GetProbes() []*SecurityConfigArgProcess {
	if x != nil {
		return x.Probes
	}
	return nil
}

type SecurityGeneralConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UpdateTimestamp int64                       `protobuf:"varint,2,opt,name=updateTimestamp,proto3" json:"updateTimestamp,omitempty"`
	Type            int32                       `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Process         *SecurityConfigProbeProcess `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	File            *SecurityConfigProbeFile    `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *SecurityGeneralConfig) Reset() {
	*x = SecurityGeneralConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityGeneralConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityGeneralConfig) ProtoMessage() {}

func (x *SecurityGeneralConfig) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityGeneralConfig.ProtoReflect.Descriptor instead.
func (*SecurityGeneralConfig) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{11}
}

func (x *SecurityGeneralConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityGeneralConfig) GetUpdateTimestamp() int64 {
	if x != nil {
		return x.UpdateTimestamp
	}
	return 0
}

func (x *SecurityGeneralConfig) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SecurityGeneralConfig) GetProcess() *SecurityConfigProbeProcess {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *SecurityGeneralConfig) GetFile() *SecurityConfigProbeFile {
	if x != nil {
		return x.File
	}
	return nil
}

type SecurityState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Available int32  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *SecurityState) Reset() {
	*x = SecurityState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityState) ProtoMessage() {}

func (x *SecurityState) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityState.ProtoReflect.Descriptor instead.
func (*SecurityState) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{12}
}

func (x *SecurityState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SecurityState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityState) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

type SecurityStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State    *SecurityState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Ip       string         `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname string         `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *SecurityStateRequest) Reset() {
	*x = SecurityStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityStateRequest) ProtoMessage() {}

func (x *SecurityStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityStateRequest.ProtoReflect.Descriptor instead.
func (*SecurityStateRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{13}
}

func (x *SecurityStateRequest) GetState() *SecurityState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SecurityStateRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SecurityStateRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type SecurityConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config        *SecurityGeneralConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ConfigVersion int32                  `protobuf:"varint,2,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
}

func (x *SecurityConfigResponse) Reset() {
	*x = SecurityConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_security_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfigResponse) ProtoMessage() {}

func (x *SecurityConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfigResponse.ProtoReflect.Descriptor instead.
func (*SecurityConfigResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{14}
}

func (x *SecurityConfigResponse) GetConfig() *SecurityGeneralConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SecurityConfigResponse) GetConfigVersion() int32 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

var File_security_proto protoreflect.FileDescriptor

var file_security_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xd4, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x64,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x08, 0x65, 0x78, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72,
	0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x3a, 0x0a, 0x0c, 0x45, 0x78,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x78, 0x0a, 0x14, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34,
	0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x31, 0x0a, 0x15, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x3d, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x52, 0x0a, 0x18, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x65, 0x72, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x9b, 0x01, 0x0a, 0x18, 0x53, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x06, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x3d, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x22, 0x78, 0x0a, 0x15, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x41, 0x0a, 0x07, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x22, 0x57,
	0x0a, 0x17, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x50, 0x72, 0x6f, 0x62, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x70, 0x72, 0x6f,
	0x62, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x06, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x22, 0x5f, 0x0a, 0x1b, 0x53, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x7e, 0x0a, 0x18, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x67, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x22, 0x5d, 0x0a, 0x1a, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x3f, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72,
	0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x67, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x06, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x22, 0xea, 0x01, 0x0a, 0x15, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x43, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x3a, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72,
	0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x22, 0x5f, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x76, 0x0a, 0x14, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7c, 0x0a,
	0x16, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x6e, 0x0a, 0x14, 0x53,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x23, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6f, 0x0a, 0x13, 0x53,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x50, 0x75, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x58, 0x0a, 0x0a, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x23, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x72, 0x79,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_security_proto_rawDescOnce sync.Once
	file_security_proto_rawDescData = file_security_proto_rawDesc
)

func file_security_proto_rawDescGZIP() []byte {
	file_security_proto_rawDescOnce.Do(func() {
		file_security_proto_rawDescData = protoimpl.X.CompressGZIP(file_security_proto_rawDescData)
	})
	return file_security_proto_rawDescData
}

var file_security_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_security_proto_goTypes = []interface{}{
	(*SecurityEvent)(nil),               // 0: securiryproto.SecurityEvent
	(*SecurityEventRequest)(nil),        // 1: securiryproto.SecurityEventRequest
	(*SecurityEventResponse)(nil),       // 2: securiryproto.SecurityEventResponse
	(*Label)(nil),                       // 3: securiryproto.Label
	(*SecurityConfigFilterFile)(nil),    // 4: securiryproto.SecurityConfigFilterFile
	(*SecurityConfigTargetFile)(nil),    // 5: securiryproto.SecurityConfigTargetFile
	(*SecurityConfigArgFile)(nil),       // 6: securiryproto.SecurityConfigArgFile
	(*SecurityConfigProbeFile)(nil),     // 7: securiryproto.SecurityConfigProbeFile
	(*SecurityConfigTargetProcess)(nil), // 8: securiryproto.SecurityConfigTargetProcess
	(*SecurityConfigArgProcess)(nil),    // 9: securiryproto.SecurityConfigArgProcess
	(*SecurityConfigProbeProcess)(nil),  // 10: securiryproto.SecurityConfigProbeProcess
	(*SecurityGeneralConfig)(nil),       // 11: securiryproto.SecurityGeneralConfig
	(*SecurityState)(nil),               // 12: securiryproto.SecurityState
	(*SecurityStateRequest)(nil),        // 13: securiryproto.SecurityStateRequest
	(*SecurityConfigResponse)(nil),      // 14: securiryproto.SecurityConfigResponse
	nil,                                 // 15: securiryproto.SecurityEvent.ExtInfoEntry
}
var file_security_proto_depIdxs = []int32{
	15, // 0: securiryproto.SecurityEvent.ext_info:type_name -> securiryproto.SecurityEvent.ExtInfoEntry
	0,  // 1: securiryproto.SecurityEventRequest.events:type_name -> securiryproto.SecurityEvent
	3,  // 2: securiryproto.SecurityConfigTargetFile.labels:type_name -> securiryproto.Label
	4,  // 3: securiryproto.SecurityConfigTargetFile.files:type_name -> securiryproto.SecurityConfigFilterFile
	5,  // 4: securiryproto.SecurityConfigArgFile.targets:type_name -> securiryproto.SecurityConfigTargetFile
	6,  // 5: securiryproto.SecurityConfigProbeFile.probes:type_name -> securiryproto.SecurityConfigArgFile
	3,  // 6: securiryproto.SecurityConfigTargetProcess.labels:type_name -> securiryproto.Label
	8,  // 7: securiryproto.SecurityConfigArgProcess.targets:type_name -> securiryproto.SecurityConfigTargetProcess
	9,  // 8: securiryproto.SecurityConfigProbeProcess.probes:type_name -> securiryproto.SecurityConfigArgProcess
	10, // 9: securiryproto.SecurityGeneralConfig.process:type_name -> securiryproto.SecurityConfigProbeProcess
	7,  // 10: securiryproto.SecurityGeneralConfig.file:type_name -> securiryproto.SecurityConfigProbeFile
	12, // 11: securiryproto.SecurityStateRequest.state:type_name -> securiryproto.SecurityState
	11, // 12: securiryproto.SecurityConfigResponse.config:type_name -> securiryproto.SecurityGeneralConfig
	1,  // 13: securiryproto.SecurityEventService.SendEvent:input_type -> securiryproto.SecurityEventRequest
	13, // 14: securiryproto.SecurityPullService.PullConfig:input_type -> securiryproto.SecurityStateRequest
	2,  // 15: securiryproto.SecurityEventService.SendEvent:output_type -> securiryproto.SecurityEventResponse
	14, // 16: securiryproto.SecurityPullService.PullConfig:output_type -> securiryproto.SecurityConfigResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_security_proto_init() }
func file_security_proto_init() {
	if File_security_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_security_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Label); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityConfigFilterFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityConfigTargetFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityConfigArgFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityConfigProbeFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityConfigTargetProcess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityConfigArgProcess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityConfigProbeProcess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityGeneralConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_security_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_security_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_security_proto_goTypes,
		DependencyIndexes: file_security_proto_depIdxs,
		MessageInfos:      file_security_proto_msgTypes,
	}.Build()
	File_security_proto = out.File
	file_security_proto_rawDesc = nil
	file_security_proto_goTypes = nil
	file_security_proto_depIdxs = nil
}
